name: Backend CI

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-ci.yml

defaults:
  run:
    working-directory: backend

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...