name: Backend CI

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-ci.yml

defaults:
  run:
    working-directory: ./backend

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
          cache-dependency-path: backend/go.sum

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go build -v ./...
    
  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go test -v ./...
